= Jolokia Client Demo

This demo project has few samples on how using https://jolokia.org[Jolokia] with JBoss Fuse.

This demo shows how to use https://jolokia.org/reference/html/clients.html#client-java[Java client] to perform the following on JBoss Fuse,

* *readData*  - sample method that reads the data from a specified MBean object name and return the attribute values as JSON

* *executeBundleOperation*  - sample method executes bundle specific operations such as`startBundle`, `stopBundle` etc.,

* *searchBundle* - search a bundle by its symbolicName and Version and return the bundleId

* *search* - search mBean objects by query and return the mBeanNames


Please check the link:./FuseJolokiaUtilMain[FuseJolokiaUtilMain] for sample invocations using this client

== License

Copyright 2017 Kamesh Sampath

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.